/**
 * 种子数据 — MCP 目录（30 个：16 编程开发 + 14 逆向工程）
 * + Operit 结构插件 + Anthropic 插件市场 + Anthropic Agent Skills
 *
 * 传输层约定：STDIO 条目默认 runInSandbox=true（Android 端在 PRoot Ubuntu 沙箱内执行），
 * requiresRootfs=true 提示需要先安装 rootfs。
 */

import type { McpServerConfig } from "./types";

export const SEED_MCP_SERVERS: McpServerConfig[] = [
  // ==========================================================================
  // 编程开发（16）
  // ==========================================================================
  {
    name: "filesystem",
    description: "官方文件系统服务器：读写文件、目录树、搜索与移动，受限在指定目录内。逆向分析时可直接读取样本目录、导出分析结果。",
    transport: "STDIO",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-filesystem", "/sdcard"],
    env: {},
    headers: {},
    enabled: false,
    runInSandbox: true,
    scope: "all",
    category: "programming",
    tags: ["官方", "文件系统", "必装"],
    vendor: "Anthropic",
    homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem",
    requiresRootfs: true,
  },
  {
    name: "github",
    description: "官方 GitHub 服务器：仓库/文件/Issue/PR 全量操作与代码搜索，逆向时拉取样本源码、提交历史与关联 CVE。",
    transport: "STDIO",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-github"],
    env: { GITHUB_PERSONAL_ACCESS_TOKEN: "<your-token>" },
    headers: {},
    enabled: false,
    runInSandbox: true,
    scope: "all",
    category: "programming",
    tags: ["官方", "代码托管", "API"],
    vendor: "Anthropic",
    homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/github",
    requiresRootfs: true,
  },
  {
    name: "git",
    description: "官方 Git 服务器：本地仓库 status/diff/log/commit/branch 操作，配合逆向工程做补丁管理与版本回溯。",
    transport: "STDIO",
    command: "uvx",
    args: ["mcp-server-git", "--repository", "/root/workspace"],
    env: {},
    headers: {},
    enabled: false,
    runInSandbox: true,
    scope: "coding",
    category: "programming",
    tags: ["官方", "版本控制"],
    vendor: "Anthropic",
    homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/git",
    requiresRootfs: true,
  },
  {
    name: "gitlab",
    description: "官方 GitLab 服务器：项目、Issue、Merge Request 与代码搜索管理。",
    transport: "STDIO",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-gitlab"],
    env: { GITLAB_PERSONAL_ACCESS_TOKEN: "<your-token>", GITLAB_API_URL: "https://gitlab.com/api/v4" },
    headers: {},
    enabled: false,
    runInSandbox: true,
    scope: "coding",
    category: "programming",
    tags: ["官方", "代码托管", "CI/CD"],
    vendor: "Anthropic",
    homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/gitlab",
    requiresRootfs: true,
  },
  {
    name: "sequential-thinking",
    description: "官方顺序思维服务器：动态分步推理、分支回溯与假设修正，逆向分析流程规划神器。",
    transport: "STDIO",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-sequential-thinking"],
    env: {},
    headers: {},
    enabled: false,
    runInSandbox: true,
    scope: "all",
    category: "programming",
    tags: ["官方", "推理", "思维链"],
    vendor: "Anthropic",
    homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking",
    requiresRootfs: true,
  },
  {
    name: "memory",
    description: "官方记忆服务器：基于知识图谱的实体/关系持久记忆，跨会话保存逆向分析结论。",
    transport: "STDIO",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-memory"],
    env: {},
    headers: {},
    enabled: false,
    runInSandbox: true,
    scope: "all",
    category: "programming",
    tags: ["官方", "记忆", "知识图谱"],
    vendor: "Anthropic",
    homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/memory",
    requiresRootfs: true,
  },
  {
    name: "fetch",
    description: "官方网页抓取服务器：URL → 干净 Markdown，自动处理编码与重定向，逆向情报收集必备。",
    transport: "STDIO",
    command: "uvx",
    args: ["mcp-server-fetch"],
    env: {},
    headers: {},
    enabled: false,
    runInSandbox: true,
    scope: "all",
    category: "programming",
    tags: ["官方", "抓取", "情报"],
    vendor: "Anthropic",
    homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/fetch",
    requiresRootfs: true,
  },
  {
    name: "sqlite",
    description: "官方 SQLite 服务器：建表/查询/分析，App 数据库取证与逆向数据落盘。",
    transport: "STDIO",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-sqlite", "--db-path", "/root/data/analysis.db"],
    env: {},
    headers: {},
    enabled: false,
    runInSandbox: true,
    scope: "coding",
    category: "programming",
    tags: ["官方", "数据库", "取证"],
    vendor: "Anthropic",
    homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/sqlite",
    requiresRootfs: true,
  },
  {
    name: "postgres",
    description: "官方 PostgreSQL 服务器：只读访问库表结构与数据，配合代码审计追踪数据流。",
    transport: "STDIO",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-postgres", "postgresql://localhost:5432/app"],
    env: {},
    headers: {},
    enabled: false,
    runInSandbox: true,
    scope: "coding",
    category: "programming",
    tags: ["官方", "数据库"],
    vendor: "Anthropic",
    homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/postgres",
    requiresRootfs: true,
  },
  {
    name: "playwright",
    description: "微软官方 Playwright MCP：无头浏览器自动化 —— 快照、点击、填表、拖拽、网络抓包，Web 逆向与爬虫利器。",
    transport: "STDIO",
    command: "npx",
    args: ["-y", "@playwright/mcp@latest"],
    env: {},
    headers: {},
    enabled: false,
    runInSandbox: true,
    scope: "all",
    category: "programming",
    tags: ["浏览器", "自动化", "爬虫", "微软"],
    vendor: "Microsoft",
    homepage: "https://github.com/microsoft/playwright-mcp",
    requiresRootfs: true,
  },
  {
    name: "context7",
    description: "Context7 文档服务器：获取任意库最新版文档与真实代码示例，离线编码不再依赖过时训练数据。",
    transport: "STDIO",
    command: "npx",
    args: ["-y", "@upstash/context7-mcp"],
    env: {},
    headers: {},
    enabled: false,
    runInSandbox: true,
    scope: "coding",
    category: "programming",
    tags: ["文档", "SDK", "Upstash"],
    vendor: "Upstash",
    homepage: "https://github.com/upstash/context7",
    requiresRootfs: true,
  },
  {
    name: "serena",
    description: "Serena：基于语言服务器（LSP）的语义级代码分析与编辑 —— 符号查找/引用/重构，免费无 token，代码审计与漏洞挖掘标配。",
    transport: "STDIO",
    command: "uvx",
    args: [
      "--from",
      "git+https://github.com/oraios/serena",
      "serena",
      "start-mcp-server",
      "--context",
      "ide-assistant",
    ],
    env: {},
    headers: {},
    enabled: false,
    runInSandbox: true,
    scope: "coding",
    category: "programming",
    tags: ["LSP", "语义分析", "代码审计", "免费"],
    vendor: "Oraios AI",
    homepage: "https://github.com/oraios/serena",
    requiresRootfs: true,
  },
  {
    name: "desktop-commander",
    description: "Desktop Commander：终端命令执行、进程管理、文件编辑与会话持久化，比 shell 更强的执行引擎。",
    transport: "STDIO",
    command: "npx",
    args: ["-y", "@wonderwhy-er/desktop-commander-mcp"],
    env: {},
    headers: {},
    enabled: false,
    runInSandbox: true,
    scope: "all",
    category: "programming",
    tags: ["终端", "命令执行", "进程"],
    vendor: "wonderwhy-er",
    homepage: "https://github.com/wonderwhy-er/DesktopCommanderMCP",
    requiresRootfs: true,
  },
  {
    name: "docker",
    description: "Docker 官方 MCP：容器/镜像/卷/网络全生命周期管理，构建隔离的动态分析环境。",
    transport: "STDIO",
    command: "npx",
    args: ["-y", "docker-mcp"],
    env: { DOCKER_HOST: "unix:///var/run/docker.sock" },
    headers: {},
    enabled: false,
    runInSandbox: true,
    scope: "coding",
    category: "programming",
    tags: ["容器", "DevOps", "官方"],
    vendor: "Docker",
    homepage: "https://github.com/docker/docker-mcp",
    requiresRootfs: true,
  },
  {
    name: "typescript",
    description: "TypeScript MCP：接入 TS 编译器的语义诊断与 AST 分析，前端代码审计与类型级漏洞发现。",
    transport: "STDIO",
    command: "npx",
    args: ["-y", "typescript-mcp", "--project", "tsconfig.json"],
    env: {},
    headers: {},
    enabled: false,
    runInSandbox: true,
    scope: "coding",
    category: "programming",
    tags: ["TypeScript", "AST", "诊断"],
    vendor: "community",
    homepage: "https://github.com/iamsurajdc/typescript-mcp",
    requiresRootfs: true,
  },
  {
    name: "semgrep",
    description: "Semgrep MCP：静态应用安全测试（SAST），规则扫描污点追踪与已知漏洞模式，代码审计第一道防线。",
    transport: "STDIO",
    command: "uvx",
    args: ["--from", "git+https://github.com/semgrep/semgrep-mcp", "semgrep-mcp"],
    env: { SEMGREP_APP_TOKEN: "<optional-token>" },
    headers: {},
    enabled: false,
    runInSandbox: true,
    scope: "coding",
    category: "programming",
    tags: ["SAST", "安全扫描", "污点分析"],
    vendor: "Semgrep",
    homepage: "https://github.com/semgrep/semgrep-mcp",
    requiresRootfs: true,
  },

  // ==========================================================================
  // 逆向工程（14）
  // ==========================================================================
  {
    name: "ghidra",
    description: "GhidraMCP：接入 NSA 开源逆向框架 Ghidra —— 反编译伪代码、函数重命名、数据类型标注、交叉引用，静态分析核心引擎。",
    transport: "STDIO",
    command: "uvx",
    args: ["--from", "git+https://github.com/LaurieWired/GhidraMCP", "ghidra_mcp"],
    env: { GHIDRA_SERVER_URL: "http://localhost:8080/api" },
    headers: {},
    enabled: false,
    runInSandbox: true,
    scope: "coding",
    category: "reverse",
    tags: ["静态分析", "反编译", "Ghidra", "NSA"],
    vendor: "LaurieWired",
    homepage: "https://github.com/LaurieWired/GhidraMCP",
    requiresRootfs: true,
  },
  {
    name: "ida-pro",
    description: "IDA Pro MCP：Hex-Rays 官方生态的 IDA 9 深度集成 —— 反编译、伪代码编辑、函数签名、调试器联动，商业级逆向工作流。",
    transport: "STDIO",
    command: "ida-pro-mcp",
    args: [],
    env: {},
    headers: {},
    enabled: false,
    runInSandbox: true,
    scope: "coding",
    category: "reverse",
    tags: ["静态分析", "反编译", "IDA", "Hex-Rays"],
    vendor: "mrexodia",
    homepage: "https://github.com/mrexodia/ida-pro-mcp",
    requiresRootfs: true,
  },
  {
    name: "radare2",
    description: "Radare2 MCP：命令行逆向框架 radare2 的 MCP 封装 —— 十六进制、反汇编、签名识别、补丁打桩，轻量级全能分析器。",
    transport: "STDIO",
    command: "uvx",
    args: ["--from", "git+https://github.com/radareorg/radare2-mcp", "r2mcp"],
    env: {},
    headers: {},
    enabled: false,
    runInSandbox: true,
    scope: "coding",
    category: "reverse",
    tags: ["静态分析", "反汇编", "radare2", "CLI"],
    vendor: "radareorg",
    homepage: "https://github.com/radareorg",
    requiresRootfs: true,
  },
  {
    name: "frida",
    description: "Frida MCP：动态插桩框架 Frida 17 集成 —— hook 任意函数、读写内存、跟踪调用、绕过反调试，移动端动态分析之王。",
    transport: "STDIO",
    command: "uvx",
    args: ["--from", "git+https://github.com/yfe404/frida-mcp", "frida-mcp"],
    env: { ANDROID_SERIAL: "127.0.0.1:5555" },
    headers: {},
    enabled: false,
    runInSandbox: true,
    scope: "coding",
    category: "reverse",
    tags: ["动态分析", "Hook", "Android", "插桩"],
    vendor: "yfe404",
    homepage: "https://github.com/yfe404/frida-mcp",
    requiresRootfs: true,
  },
  {
    name: "binary-ninja",
    description: "Binary Ninja MCP：商业二进制分析平台集成 —— HLIL/MLIL/LLIL 三层中间表示、跨平台反编译、脚本化批处理。",
    transport: "STDIO",
    command: "uvx",
    args: ["--from", "git+https://github.com/felddo/binary-ninja-mcp", "binary-ninja-mcp"],
    env: {},
    headers: {},
    enabled: false,
    runInSandbox: true,
    scope: "coding",
    category: "reverse",
    tags: ["静态分析", "IL", "商业工具"],
    vendor: "community",
    homepage: "https://binary.ninja/",
    requiresRootfs: true,
  },
  {
    name: "jadx",
    description: "Jadx MCP：Java/Android 反编译器集成 —— DEX→Java 源码、资源还原、混淆映射，APK 静态审计首选。",
    transport: "STDIO",
    command: "uvx",
    args: ["--from", "git+https://github.com/rglx/jadx-mcp", "jadx-mcp"],
    env: { JADX_PATH: "/opt/jadx/bin/jadx" },
    headers: {},
    enabled: false,
    runInSandbox: true,
    scope: "coding",
    category: "reverse",
    tags: ["Android", "APK", "反编译", "DEX"],
    vendor: "community",
    homepage: "https://github.com/skylot/jadx",
    requiresRootfs: true,
  },
  {
    name: "apktool",
    description: "Apktool MCP：APK 解包/重打包 —— smali 汇编、AndroidManifest 解析、资源解密，改包与去签名验证工作流。",
    transport: "STDIO",
    command: "uvx",
    args: ["--from", "git+https://github.com/aklinker1/apktool-mcp", "apktool-mcp"],
    env: {},
    headers: {},
    enabled: false,
    runInSandbox: true,
    scope: "coding",
    category: "reverse",
    tags: ["Android", "smali", "解包", "重打包"],
    vendor: "community",
    homepage: "https://apktool.org/",
    requiresRootfs: true,
  },
  {
    name: "android-tools",
    description: "Android ADB 工具集 MCP：设备管理、adb shell、logcat 抓取、dumpsys 解析、无线调试，真机/模拟器动态分析通道。",
    transport: "STDIO",
    command: "uvx",
    args: ["--from", "git+https://github.com/mobile-reverse/android-tools-mcp", "android-tools-mcp"],
    env: { ADB_SERVER_PORT: "5037" },
    headers: {},
    enabled: false,
    runInSandbox: true,
    scope: "coding",
    category: "reverse",
    tags: ["Android", "ADB", "logcat", "动态分析"],
    vendor: "community",
    homepage: "https://developer.android.com/tools/adb",
    requiresRootfs: true,
  },
  {
    name: "shodan",
    description: "Shodan MCP：全网设备搜索引擎 —— 端口/服务/漏洞指纹查询、地理定位，互联网暴露面情报收集。",
    transport: "STDIO",
    command: "uvx",
    args: ["--from", "git+https://github.com/ascii-dresden/mcp-server-shodan", "mcp-server-shodan"],
    env: { SHODAN_API_KEY: "<your-key>" },
    headers: {},
    enabled: false,
    runInSandbox: true,
    scope: "coding",
    category: "reverse",
    tags: ["情报", "网络侦察", "IoT"],
    vendor: "community",
    homepage: "https://www.shodan.io/",
    requiresRootfs: true,
  },
  {
    name: "nmap",
    description: "Nmap MCP：网络发现与端口扫描 —— 服务/OS 识别、NSE 脚本执行、内网渗透前侦察。",
    transport: "STDIO",
    command: "uvx",
    args: ["--from", "git+https://github.com/ascii-dresden/mcp-server-nmap", "mcp-server-nmap"],
    env: {},
    headers: {},
    enabled: false,
    runInSandbox: true,
    scope: "coding",
    category: "reverse",
    tags: ["端口扫描", "网络侦察", "NSE"],
    vendor: "community",
    homepage: "https://nmap.org/",
    requiresRootfs: true,
  },
  {
    name: "burp-suite",
    description: "Burp Suite MCP：Web 安全测试平台集成 —— 请求重放、扫描器联动、Intruder 自动化，Web 逆向与渗透核心。",
    transport: "STDIO",
    command: "uvx",
    args: ["--from", "git+https://github.com/dotbygrave/mcp-server-burp", "mcp-server-burp"],
    env: { BURP_API_URL: "http://localhost:1337/v0.1" },
    headers: {},
    enabled: false,
    runInSandbox: true,
    scope: "coding",
    category: "reverse",
    tags: ["Web安全", "抓包", "渗透", "PortSwigger"],
    vendor: "community",
    homepage: "https://portswigger.net/burp",
    requiresRootfs: true,
  },
  {
    name: "yara",
    description: "YARA MCP：恶意软件特征规则引擎 —— 编写/匹配/扫描规则，样本家族归类与威胁狩猎。",
    transport: "STDIO",
    command: "uvx",
    args: ["--from", "git+https://github.com/chainguard-dev/mcp-server-yara", "mcp-server-yara"],
    env: {},
    headers: {},
    enabled: false,
    runInSandbox: true,
    scope: "coding",
    category: "reverse",
    tags: ["特征识别", "恶意软件", "威胁狩猎"],
    vendor: "community",
    homepage: "https://virustotal.github.io/yara/",
    requiresRootfs: true,
  },
  {
    name: "capstone",
    description: "Capstone MCP：轻量反汇编引擎 —— 多架构（x86/ARM/MIPS/ELF/PE）指令级反汇编与熵分析，脚本化二进制批处理。",
    transport: "STDIO",
    command: "uvx",
    args: ["--from", "git+https://github.com/angelocarly/mcp-server-capstone", "mcp-server-capstone"],
    env: {},
    headers: {},
    enabled: false,
    runInSandbox: true,
    scope: "coding",
    category: "reverse",
    tags: ["反汇编", "多架构", "引擎"],
    vendor: "community",
    homepage: "https://www.capstone-engine.org/",
    requiresRootfs: true,
  },
  {
    name: "volatility",
    description: "Volatility MCP：内存取证框架 —— 进程/网络/注册表/凭证提取，恶意代码内存行为分析与样本取证。",
    transport: "STDIO",
    command: "uvx",
    args: ["--from", "git+https://github.com/volatilityfoundation/mcp-server-volatility", "mcp-server-volatility"],
    env: {},
    headers: {},
    enabled: false,
    runInSandbox: true,
    scope: "coding",
    category: "reverse",
    tags: ["内存取证", "恶意软件", "取证"],
    vendor: "community",
    homepage: "https://github.com/volatilityfoundation/volatility3",
    requiresRootfs: true,
  },
];

// ---------------------------------------------------------------------------
// Operit 结构插件（mcp_config.json 约定：STDIO 沙箱 + 默认停用）
// ---------------------------------------------------------------------------

export interface SeedPlugin {
  name: string;
  description: string;
  version: string;
  author: string;
  format: "operit" | "anthropic-marketplace" | "anthropic-skill";
  pluginType: string;
  config: Record<string, unknown>;
  skillBody?: string;
  enabled: boolean;
  installed: boolean;
  sourceUrl?: string;
  repo?: string;
  tags: string[];
}

export const SEED_PLUGINS: SeedPlugin[] = [
  {
    name: "operit-mcp-bridge",
    description: "Operit 官方 MCP 桥接插件：将任意 mcpServers 配置一键注入 Operit 运行时，STDIO 强制沙箱执行。",
    version: "1.2.0",
    author: "AAswordman",
    format: "operit",
    pluginType: "mcp",
    config: {
      mcpServers: {
        "operit-bridge": {
          command: "npx",
          args: ["-y", "operit-mcp-bridge"],
          env: { OPERIT_HOME: "/sdcard/Operit" },
          runInSandbox: true,
          disabled: false,
        },
      },
    },
    enabled: false,
    installed: true,
    sourceUrl: "https://github.com/AAswordman/Operit",
    repo: "AAswordman/Operit",
    tags: ["Operit", "桥接", "官方"],
  },
  {
    name: "operit-r0capture",
    description: "Operit 社区抓包插件：基于 r0capture 的全场景 Android 抓包，SSL Pinning 旁路，输出 HAR/PcapNG。",
    version: "0.9.3",
    author: "r0ysue",
    format: "operit",
    pluginType: "mcp",
    config: {
      mcpServers: {
        "r0capture": {
          command: "python",
          args: ["-m", "r0capture.mcp", "--device", "usb"],
          env: { ANDROID_SERIAL: "127.0.0.1:5555" },
          runInSandbox: true,
          disabled: false,
        },
      },
    },
    enabled: false,
    installed: true,
    sourceUrl: "https://github.com/r0ysue/r0capture",
    repo: "r0ysue/r0capture",
    tags: ["Operit", "抓包", "动态分析"],
  },
  {
    name: "operit-frida-tools",
    description: "Operit 社区 Frida 工具箱：hook 脚本热加载、ObjC/Java 桥、反调试绕过一键化。",
    version: "2.1.1",
    author: "hluwa",
    format: "operit",
    pluginType: "mcp",
    config: {
      mcpServers: {
        "frida-tools": {
          command: "uvx",
          args: ["--from", "git+https://github.com/hluwa/operit-frida-tools", "frida-tools-mcp"],
          env: { FRIDA_VERSION: "17.0.0" },
          runInSandbox: true,
          disabled: false,
        },
      },
    },
    enabled: false,
    installed: true,
    sourceUrl: "https://github.com/hluwa",
    repo: "hluwa/operit-frida-tools",
    tags: ["Operit", "Frida", "Hook"],
  },
  {
    name: "operit-signature-kill",
    description: "Operit 社区签名校验绕过插件：常见签名校验 / root 检测 / 模拟器检测批量旁路。",
    version: "1.4.0",
    author: "Operit-Community",
    format: "operit",
    pluginType: "mcp",
    config: {
      mcpServers: {
        "sigkill": {
          command: "python",
          args: ["-m", "sigkill.mcp"],
          env: {},
          runInSandbox: true,
          disabled: false,
        },
      },
    },
    enabled: false,
    installed: true,
    sourceUrl: "https://github.com/topics/operit-plugin",
    repo: "operit-community/signature-kill",
    tags: ["Operit", "反混淆", "绕过"],
  },
  {
    name: "anthropic-code-review",
    description: "Anthropic 官方 Claude Code 插件市场 · 代码审查：深度审查变更集，安全/性能/可维护性多维报告。",
    version: "1.0.6",
    author: "anthropic",
    format: "anthropic-marketplace",
    pluginType: "skill",
    config: {
      name: "code-review",
      source: "./plugins/code-review",
      description: "深度审查变更集，输出安全/性能/可维护性多维报告",
      category: "code-quality",
    },
    enabled: false,
    installed: true,
    sourceUrl: "https://github.com/anthropics/claude-code",
    tags: ["Anthropic", "官方", "代码审查"],
  },
  {
    name: "anthropic-security-review",
    description: "Anthropic 官方 Claude Code 插件市场 · 安全审计：OWASP Top 10 与供应链风险扫描审查。",
    version: "1.0.4",
    author: "anthropic",
    format: "anthropic-marketplace",
    pluginType: "skill",
    config: {
      name: "security-review",
      source: "./plugins/security-review",
      description: "OWASP Top 10 与供应链风险扫描审查",
      category: "security",
    },
    enabled: false,
    installed: true,
    sourceUrl: "https://github.com/anthropics/claude-code",
    tags: ["Anthropic", "官方", "安全审计"],
  },
  {
    name: "skill-pdf",
    description: "Anthropic 官方 Agent Skill：PDF 表单填充、文本抽取与合并拆分，逆向报告自动生成。",
    version: "1.0.0",
    author: "anthropics",
    format: "anthropic-skill",
    pluginType: "skill",
    config: { name: "pdf", description: "PDF 表单填充、文本抽取与合并拆分" },
    skillBody:
      "---\nname: pdf\ndescription: PDF 表单填充、文本抽取、合并拆分与页面转换。适用于需要处理 PDF 文档报告的场景。\nlicense: MIT\n---\n\n# PDF 处理技能\n\n## 何时使用\n- 填充 PDF 表单字段\n- 从 PDF 抽取文本与表格\n- 合并/拆分/旋转 PDF 页面\n\n## 操作指南\n1. 使用 pypdf 库读取文档结构\n2. 表单填充前先枚举 AcroForm 字段\n3. 大文件使用增量写入避免内存峰值",
    enabled: false,
    installed: true,
    sourceUrl: "https://github.com/anthropics/skills",
    tags: ["Anthropic", "官方", "文档", "Skill"],
  },
  {
    name: "skill-artifacts-builder",
    description: "Anthropic 官方 Agent Skill：构建交互式单文件 HTML 应用（React/Tailwind），快速产出分析报告可视化。",
    version: "1.0.0",
    author: "anthropics",
    format: "anthropic-skill",
    pluginType: "skill",
    config: { name: "artifacts-builder", description: "构建交互式单文件 HTML 工件" },
    skillBody:
      "---\nname: artifacts-builder\ndescription: 构建交互式单文件 HTML 应用（内联 React + Tailwind），生成可直接在浏览器打开的可视化工件。\nlicense: MIT\n---\n\n# Artifacts 构建技能\n\n## 何时使用\n- 用户需要交互式数据可视化\n- 生成独立可分发的 HTML 工件\n\n## 约束\n- 所有 JS/CSS 必须内联\n- 无外部网络依赖\n- 优先使用 React 18 + Tailwind CDN 内联替换",
    enabled: false,
    installed: true,
    sourceUrl: "https://github.com/anthropics/skills",
    tags: ["Anthropic", "官方", "前端", "Skill"],
  },
  {
    name: "skill-reverse-workflow",
    description: "社区 Agent Skill：标准逆向工作流 —— 静态初筛 → 动态验证 → 报告归档三段式 SOP。",
    version: "0.7.2",
    author: "android-guru-community",
    format: "anthropic-skill",
    pluginType: "skill",
    config: { name: "reverse-workflow", description: "标准逆向工程三段式工作流" },
    skillBody:
      "---\nname: reverse-workflow\ndescription: 逆向工程标准作业流程：静态初筛（jadx/ghidra）→ 动态验证（frida/logcat）→ 结论归档（markdown 报告）。\nlicense: Apache-2.0\n---\n\n# 逆向工作流\n\n## 阶段一 · 静态初筛\n1. apktool 解包提取 manifest 与资源\n2. jadx 反编译定位入口与关键类\n3. ghidra 分析 native so 导出表\n\n## 阶段二 · 动态验证\n1. frida hook 关键函数确认行为\n2. logcat / tcpdump 采集运行时证据\n\n## 阶段三 · 结论归档\n按「样本信息 → 行为链 → IOCs → 复现步骤」输出报告",
    enabled: false,
    installed: true,
    sourceUrl: "https://github.com/AceGuru-mjh",
    tags: ["Skill", "逆向", "工作流", "社区"],
  },
];
